public class Even_Fibonacci_Numbers {

  /*
      Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
      
      By starting with 1 and 2, the first 10 terms will be:
      1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

      By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
  */

  public static void main (String[] args) {
      fibonacci(1, 2);
  }

  static int sum = 0, fibonacciSequence = 0;

  public static void fibonacci (int i, int j) {

      fibonacciSequence = j;
      if (fibonacciSequence <= 4000000) { // 4 million
          if (j % 2 == 0) {
              sum += j;
          }
          fibonacci(j, i + j);
      } else {
          System.out.println(sum);
      }
  }
}