/*
	Each new term in the Fibonacci sequence is generated by adding the previous 
	two terms. By starting with 1 and 2, the first 10 terms will be:
	1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

	By considering the terms in the Fibonacci sequence whose values do not 
	exceed n, find the sum of the even-valued terms.
*/

fn fibonacci_evens_sum(number: usize) -> usize {
    let mut result = 0;
    let (mut previous, mut current) = (1, 2);
    while current <= number {
        if current % 2 == 0 {
            result += current;
        }
        let auxiliary = current;
        current += previous;
        previous = auxiliary;
    }
    return result;
}

fn main() {
    println!("{}", fibonacci_evens_sum(4000000));
}