/*Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed n, find the sum of the even-valued terms. -IN KOTLIN
*/

fun fibEvenSum(number: Int){
var lastNum: Int = 1
var currentNum: Int = 2
var total: Int = 0
	while (currentNum <= number){
		if (currentNum % 2 == 0){
			total = total + currentNum
        else 
            total = total + 0
        }
	tempCurrentNum = currentNum
	currentNum = currentNum + lastNum
	lastNum = tempCurrentNum
    }
return total
}

print(fibEvenSum(20))



